export const SEARCH_MOVIE_START = 'SEARCH_MOVIE_START';
export const SEARCH_MOVIE_COMPLETE = 'SEARCH_MOVIE_COMPLETE';
export const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR';

export const SEARCH_MOVIE_BYID_START = 'SEARCH_MOVIE_BYID_START';
export const SEARCH_MOVIE_BYID_COMPLETE = 'SEARCH_MOVIE_BYID_COMPLETE';
export const SEARCH_MOVIE_BYID_ERROR = 'SEARCH_MOVIE_BYID_ERROR';

export const CLEAR_MOVIES = 'CLEAR_MOVIES';
